version: '3.8'
services:
  orderservice:
    build: ./OrderService
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  userservice:
    build: ./UserService
    ports:
      - "3001:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
